### ISSUE TITLE
The mod mistake one side as the loading bar in 1.16.1 with optifine

### ISSUE THREAD

**Issue by Fox2Code** [A5b84/dark-loading-screen#1]
The screenshot is self-explanatory

![LoadingRed](https://user-images.githubusercontent.com/42963271/86532511-ea316b80-beca-11ea-99c4-0dfee0ef450c.png)

:3

Also added logs: [2020-07-05-1.log](https://github.com/A5b84/dark-loading-screen/files/4874888/2020-07-05-1.log)

**Comment by A5b84** [comment]
It's caused by OptiFine, should be pretty easy to fix so I guess I'll do that (at some point)

Meanwhile you can use [this](https://www.curseforge.com/minecraft/texture-packs/dark-loading-screen) instead of my mod as a dirty workaround

**Comment by Fox2Code** [comment]
I found that it thinks that the left thingy is the bar color

https://github.com/A5b84/dark-loading-screen/blob/master/src/main/java/io/github/a5b84/darkloadingscreen/mixin/SplashScreenMixin.java
So maybe putting the Bar color index and the Optifine color index and give appropriate value depending on if Optifine is loaded or not

Also alternatively you could do a hax to inject `assets/minecraft/optifine/color.properties` dynamically if Optifine is loaded

For now, I put the bar color the sames as the border color :3

**Comment by A5b84** [comment]
A 1.16 snapshot (20w22a) had the same issue because the way the bar was rendered before was with 3 rectangles on top of each other (a black one for the outline, then a white one (same color as the vanilla background), and then the red one), and it was changed to 4 1-wide black rectangles and a red one, and I think OptiFine just reverts that change

Anyway, using the old mixins when optifine is present should fix it, haven't tested yet but it should be working

**Comment by A5b84** [comment]
Turns out that OptiFIne actually calls `fill` one more time that vanilla and it doesn't appear to be visible (it's the white one, maybe it's for the bar background but I'm too lazy to check ¯\\\_(ツ)\_/¯ )

Anyway, easy to fix so expect a new version soon :>

![OptiFine fill ordinals](https://user-images.githubusercontent.com/42934711/86590492-00edc600-bf90-11ea-8c3b-dae0cedae259.png)
