### ISSUE TITLE
[Fabric 1.17.1] Crash at startup

### ISSUE THREAD

**Issue by maicol07** [A5b84/dark-loading-screen#18]
Error:

```
java.lang.NullPointerException: Cannot read field "bgR" because "io.github.a5b84.darkloadingscreen.Mod.config" is null
```

Crash report: [https://pastebin.com/x9XyEUgY](https://pastebin.com/x9XyEUgY)

Crash log: https://pastebin.com/vN18pU03

**Comment by A5b84** [comment]
Couldn't reproduce but it should be fixed now, feel free to reopen the issue if it's still not working

**Comment by maicol07** [comment]
Now I get an Iris exception, but I don't know if it is related to the mod:
```
java.lang.NullPointerException: Cannot invoke "net.coderbot.iris.pipeline.PipelineManager.getPipeline()" because the return value of "net.coderbot.iris.Iris.getPipelineManager()" is null
```

I've digged a bit on previous version and it seems that the issue was some incompatibility with Flytre Lib v1 (I read it's a complete rewrite).
I can load the game without the Iris exception by disabling FlytreLib. However, with the previous version of Dark Loading Screen I didn't have that issue, although it was incompatible FlytreLib (disabling DLS worked)

**Comment by A5b84** [comment]
I doubt this is caused by mod but I think it's because of another mod messing with other mods' initializers (mine was supposed to load the config but it wasn't called and crashed your game, I guess Iris' creates their `PipelineManager`)

I very vaguely remember people saying things about Not Enough Crashes and it does appear to do something with mod entrypoints [here](https://github.com/natanfudge/Not-Enough-Crashes/blob/2233da3e41ecfbdeeb3b8b298c5a0a9c663c2515/fabric/src/main/java/fudge/notenoughcrashes/mixins/client/CatchInitMInecraftClientMixin.java#L28-L39) so I guess you can try removing it
