### ISSUE TITLE
Thorny edges of a logos letters

### ISSUE THREAD

**Issue by kokurosa** [A5b84/dark-loading-screen#35]
![huge_2024-08-30_00 33 48](https://github.com/user-attachments/assets/18584530-31cd-4075-b40d-fc926cc2e953)
By me it seems that original Minecraft loading screen appears as vector image (have no problems with original), and the one of my most loved mod do it with pixelated image - i don't know why, but mods logo have so sharp teeth, that my monitor 23,8 in diagonal and 1920x1080 can show me them, it annoys me. Can this be fixed? By the way, I had read closed issues earlier, and it seems you, developer, care about the mod, it's somehow makes me happy. Thank you earlier!

**Comment by A5b84** [comment]
Hi, it looks as smooth as the vanilla logo on my machine (also 1920x1080)

![image](https://github.com/user-attachments/assets/25346ed7-f65c-44f0-9857-4b8824d42553)

![image](https://github.com/user-attachments/assets/458bc388-04e5-41ba-a623-b8aaf1257d32)

This might be caused by another mod, could you check if this also happens when my mod is not installed?

(For reference the vanilla logo is a regular 512x512 texture and I don't think you can change it using resource packs, although you may be able to replace it with a higher res image by directly modifying the version jar)

**Comment by kokurosa** [comment]
![Screenshot_3](https://github.com/user-attachments/assets/f7aa1637-3cda-48b8-8200-269a3369a552)
![Screenshot_2](https://github.com/user-attachments/assets/efbca69b-9c7c-4b4e-8745-45a868e5919b)
Turns out that was because of PuzzleAPI (and because I was lazy to investigate it easily by old-old method...)
Also tha configuration is for Optifine, the hint behind button says, but I use Iris, don't know how logo will look with Optifine
And here is logo without your mod and with Puzzle custom loadscreen is ON, that was easy, turns out!
![Screenshot_4](https://github.com/user-attachments/assets/2a308c48-3c62-49a7-9f1c-968a8d12ac08)

Thanks for your time, I happy for your mod and wish you all the best!

**Comment by A5b84** [comment]
Glad to see you found a solution :)
